pcap-monitor: Fix build error
g_clear_handle_id was introduced in GLib 2.56 so it was not available in our target (GLIB_VERSION_MAX_ALLOWED),
leading to the following error:

	c-sources/pcap-monitor.c: In function ‘handle_error’:

	c-sources/pcap-monitor.c:415:13: error:
	     warning: Not available before
	      415 |   g_clear_handle_id (&self->await_both_errors_id, g_source_remove);
	          |             ^~~~~~~~~~~~~~~~~~~~~~~
	    |
	415 |   g_clear_handle_id (&self->await_both_errors_id, g_source_remove);
	    |             ^

Weirdly, it did not seem to affect the build status.